version: '3'


services:
  php:
    image: backend_php

  nginx:
    image: jguyomard/laravel-nginx
    ports:
      - 8080:80

  frontend:
    image: frontend
    ports:
      - 3000:80

  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
      - "3306:3306"

volumes:
  mysqldata:
